databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: video-backend
    env: java
    plan: free
    buildCommand: cd backend && ./gradlew bootJar --no-daemon
    startCommand: cd backend && java -jar build/libs/backend-*.jar
    envVars:
      - key: PEXELS_API_KEY
        value: 6PajgCRIIxWDvZ9YjW4kKiAG3dMGUYJs4TEJufJiPGd332pTbQ89dmP4
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx512m
