spring.application.name=backend
server.port=8080

# Pexels API Configuration
# Get a free API key from https://www.pexels.com/api/
pexels.api.key=${PEXELS_API_KEY:NjajgCRIIxWDvZ9YjW4kKiAG3dMGUYJs4TEJufJiPGd332pTbQ89dmP4}
pexels.api.url=https://api.pexels.com/videos
